### ISSUE TITLE
Investigate moving optional fields to the header

### ISSUE THREAD

**Issue by Yoric** [Yoric/binjs-ref#25]
On Bugzilla, @arai-a suggested that we could get rid of `null` values in optional fields. The only way to do this in a multipart-style encoder would be to move optional fields to the header.

# Example

For loops have optional values `init`, `test`, `update`.  There is a single entry in the grammar table for `ForStatement` which looks like a (binarified) version of:

```ocaml
ForStatement ["init", "test", "update"] // Entry 42 in the table
```

If we need to represent `for(;;) { ... }`, we'll write something that amounts to:

```yaml
ForStatement {
  init: BINJS_Null,
  test: BINJS_Null,
  update: BINJS_Null,
  body: ...
}
```

or, in binary, the sequence

```js
[/* grammar index */ 42,  /* field `init` */ 0, /* field `test` */ 0, /* field `update` */ 0, /* field `body` */ ...]
```

The parser reads the values `BINJS_Null`, deduces that fields `init`, `test` and `update` are omitted and replaces them with the grammar default value.

An alternative manner of denoting that fields are omitted would be to take advantage of our header mechanism to specify that the file contains a variant of `ForStatement` that omits fields `init`, `test`, `update`.

```ocaml
ForStatement ["init", "test", "update", "body"] // Entry 42 in the table
ForStatement ["body"] // Entry 43 in the table
```

This would let us represent

`for(;;) { ... }`

as 

```yaml
ForStatement {
  init: BINJS_Null,
  test: BINJS_Null,
  update: BINJS_Null,
  body: ...
}
```

or, in binary

```js
[/* grammar index */ 43, /* field `body` */ ...]
```
